name = "backend"
compatibility_date = "2024-08-31"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTQ4ODJhNWEtYzE2OC00ZDdkLWI5MDMtY2QyZGNmOTE4NWMwIiwidGVuYW50X2lkIjoiOGIwYWVjNzQwYzU5NWViZjdlMzQ4MTcxNTUxZWZiNmEyMmNiODlkZjhkOGNhZDU5MWZmNzgzMGM5NmJmODdjYSIsImludGVybmFsX3NlY3JldCI6ImYxYzg4YjRhLTFlYTUtNGU5Mi1iMzM2LTQxZjIwNzQ5ZTg5ZiJ9.2rTzkGH0Tlaco7rkQDzDsTfLsJAyV0H3NkINbHo31pA"
JWT_SECRET="ANSHUKRSINGH@anshux1"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
